project:
  output-dir: docs/ru
  render: 
    - index-ru.qmd

website:
  title: "Анастасия Еннэ"
  search: false
  navbar:
    tools: 
      - href: https://github.com/enne-anastasia
        icon: "github"
      - href: https://www.linkedin.com/in/enne-anastasia/
        icon: "linkedin"
      - href: https://t.me/enne_anastasia
        icon: "telegram"
      - href: mailto:anastasiia.enne@uni-bielefeld.de
        icon: "envelope-fill"

lang: ru