project:
  type: website
  output-dir: docs
  render: 
    - index.qmd

website:
  title: "Anastasiia Enne"
  search: false
  navbar:
    left:
      - text: Contacts
        menu: 
          - href: https://github.com/enne-anastasia
            icon: "github"
            text: "GitHub"
          - href: https://www.instagram.com/enne.anastasia/
            icon: "instagram"
            text: "Instagram"
          - href: https://t.me/enne_anastasia
            icon: "telegram"
            text: "Telegram"
          - href: https://www.linkedin.com/in/enne-anastasia/
            icon: "linkedin"
            text: "LinkedIn"

format:
  html:
    theme: lux
    css: styles.css
    toc: true
